"""Mako template for new migration files."""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f00e92dd24'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('hero_stats', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'hero_stats')
    # ### end Alembic commands ###
